In [1]:
import numpy as np
import pandas as pd

training_data = pd.read_csv('ml_classification (1)\storepurchasedata.csv')

training_data.describe()

X = training_data.iloc[:, :-1].values
y = training_data.iloc[:,-1].values

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size =.20,random_state=0)

In [9]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [11]:
X_test

array([[ 0.08291162,  0.54818427],
       [-0.0686982 ,  0.19018638],
       [ 0.31032636,  0.13904382],
       [-1.28157679,  0.03675871],
       [-0.82674732,  1.5710354 ],
       [-0.44772276, -0.11666896],
       [ 0.53774109, -1.39523286],
       [-0.75094241, -0.47466685]])

In [12]:
from sklearn.neighbors import KNeighborsClassifier
# minkowski is for ecledian distance
classifier = KNeighborsClassifier(n_neighbors = 5, metric = 'minkowski', p = 2)

In [14]:
classifier.fit(X_train, y_train)

KNeighborsClassifier()

In [16]:
y_pred = classifier.predict(X_test)
y_prob = classifier.predict_proba(X_test)[:,1]

In [18]:
y_pred

array([1, 1, 1, 0, 1, 0, 0, 0], dtype=int64)

In [17]:
y_prob

array([1. , 0.6, 0.8, 0. , 0.8, 0.2, 0.4, 0. ])